$('#modalContainer').html("<%= j render 'sparc_requests/form', sparc_request: @sparc_request, is_draft: @is_draft %>")
setRequiredFields()
initializeTooltips()
initializeSelectpickers()
initializePrimaryPITypeahead()
$('#modalContainer').modal('show')
