$('#modalContainer').html("<%= j render 'sparc_requests/form', sparc_request: @sparc_request %>")
setRequiredFields()
initializeTooltips()
initializeSelectpickers()
initializeProtocolTypeahead()
initializePrimaryPITypeahead()
$('#modalContainer').modal('show')