$('#modalContainer').html("<%= j render 'sparc_requests/form', sparc_request: @sparc_request %>")
setRequiredFields()
initializeProtocolTypeahead()
initializePrimaryPITypeahead()
loadI2B2Queries("<%= current_user.id %>")
$('#modalContainer').modal('show')
