default: &default
  adapter: mysql2
  username: root
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: biobank_development

test:
  <<: *default
  database: biobank_test
